version: "3.7"
services:
  nid-evaluator:
    container_name: nid-evaluator
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app
    environment:
      - VIRTUAL_HOST=${APP_URL}
    expose:
      - 6791
    ports:
      - 6791:6791
    networks:
      - development_network
    env_file:
      - ../.env
networks:
  development_network:
    external:
      name: docker_development_network_01
